<!-- NG-HEADER: Nombre de archivo: SalesView.vue -->
<!-- NG-HEADER: Ubicación: frontend-vue/src/modules/sales/views/SalesView.vue -->
<!-- NG-HEADER: Descripción: Listado operativo y métricas de ventas. -->
<!-- NG-HEADER: Lineamientos: Ver AGENTS.md -->
<script setup lang="ts">import { onMounted, ref, watch } from 'vue';import { getChannelsReport,getMarginReport,listSales } from '../../../services/sales';import { getHttpErrorMessage } from '../../../services/http'
const rows=ref<any[]>([]),page=ref(1),pages=ref(1),status=ref<string|null>(null),payment=ref<string|null>(null),from=ref(''),to=ref(''),loading=ref(false),error=ref(''),margin=ref<any>({}),channels=ref<any[]>([])
async function load(){loading.value=true;try{const [data,m,c]=await Promise.all([listSales({page:page.value,page_size:25,status:status.value||undefined,payment_status:payment.value||undefined,dt_from:from.value||undefined,dt_to:to.value||undefined}),getMarginReport(),getChannelsReport()]);rows.value=data.items;pages.value=data.pages;margin.value=m;channels.value=c.items}catch(e){error.value=getHttpErrorMessage(e)}finally{loading.value=false}} watch([page,status,payment,from,to],load);onMounted(load)
</script><template><v-container fluid class="py-8"><div class="d-flex justify-space-between mb-6"><div><h1 class="text-h4">Ventas</h1><p class="text-medium-emphasis">Operación, cobros y rentabilidad</p></div><v-btn color="primary" to="/ventas/nueva" prepend-icon="mdi-cash-register">Nueva venta</v-btn></div><v-alert v-if="error" type="error" class="mb-4">{{error}}</v-alert>
<v-row class="mb-4"><v-col v-for="key in ['revenue','cost','margin','cost_coverage_percent']" :key="key"><v-card><v-card-text><div class="text-caption">{{key}}</div><div class="text-h6">{{Number(margin[key]||0).toLocaleString('es-AR')}}</div></v-card-text></v-card></v-col></v-row>
<v-card><v-card-text class="d-flex ga-3 flex-wrap"><v-select v-model="status" :items="['BORRADOR','CONFIRMADA','ENTREGADA','ANULADA']" label="Estado" clearable hide-details/><v-select v-model="payment" :items="['PENDIENTE','PARCIAL','PAGADA']" label="Pago" clearable hide-details/><v-text-field v-model="from" type="date" label="Desde" hide-details/><v-text-field v-model="to" type="date" label="Hasta" hide-details/></v-card-text><v-data-table :items="rows" :loading="loading" :headers="[{title:'#',key:'id'},{title:'Fecha',key:'sale_date'},{title:'Cliente',key:'customer_name'},{title:'Canal',key:'channel_name'},{title:'Estado',key:'status'},{title:'Pago',key:'payment_status'},{title:'Total',key:'total'},{title:'Saldo',key:'balance'},{title:'',key:'actions'}]" hide-default-footer><template #item.actions="{item}"><v-btn :to="`/ventas/${item.id}`" variant="text">Abrir</v-btn></template></v-data-table><v-card-actions><v-pagination v-model="page" :length="Math.max(1,pages)"/></v-card-actions></v-card>
<v-card class="mt-4"><v-card-title>Canales</v-card-title><v-chip v-for="ch in channels" :key="ch.channel_name" class="ma-2">{{ch.channel_name}} · {{ch.total}}</v-chip></v-card></v-container></template>
