<!-- NG-HEADER: Nombre de archivo: DriveSyncView.vue -->
<!-- NG-HEADER: Ubicación: frontend-vue/src/modules/admin/views/DriveSyncView.vue -->
<!-- NG-HEADER: Descripción: Operación, historial y reintentos de sincronización Drive. -->
<!-- NG-HEADER: Lineamientos: Ver AGENTS.md -->
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { cancelDriveRun, getDriveRun, listDriveRuns, openDriveEvents, retryDriveRun, startDriveRun, type DriveRun } from '../../../services/adminOperations'
import { getHttpErrorMessage } from '../../../services/http'
import { useToastStore } from '../../../app/notifications/store'

const runs = ref<DriveRun[]>([]); const selected = ref<DriveRun | null>(null); const loading = ref(false); const busy = ref(false); const error = ref(''); const selectedItems = ref<number[]>([])
const toasts = useToastStore(); let socket: WebSocket | null = null
const active = computed(() => runs.value.find((run) => ['queued','running','cancel_requested'].includes(run.status)))
async function refresh(){loading.value=true;try{runs.value=(await listDriveRuns()).items;if(selected.value)selected.value=await getDriveRun(selected.value.id)}catch(e){error.value=getHttpErrorMessage(e)}finally{loading.value=false}}
async function selectRun(run:DriveRun){selected.value=await getDriveRun(run.id);selectedItems.value=(selected.value.items??[]).filter((item)=>['failed','skipped'].includes(item.status)).map((item)=>item.id)}
async function start(){busy.value=true;try{await startDriveRun();toasts.show('Sincronización iniciada','success');await refresh()}catch(e){error.value=getHttpErrorMessage(e)}finally{busy.value=false}}
async function cancel(){if(!active.value)return;busy.value=true;try{await cancelDriveRun(active.value.id);await refresh()}catch(e){error.value=getHttpErrorMessage(e)}finally{busy.value=false}}
async function retry(){if(!selected.value||!selectedItems.value.length)return;busy.value=true;try{await retryDriveRun(selected.value.id,selectedItems.value);toasts.show('Reintento encolado','success');await refresh()}catch(e){error.value=getHttpErrorMessage(e)}finally{busy.value=false}}
onMounted(()=>{refresh();socket=openDriveEvents();socket.onmessage=()=>refresh()});onUnmounted(()=>socket?.close())
</script>
<template><v-container fluid class="py-8"><div class="d-flex flex-wrap justify-space-between align-center ga-3 mb-6"><div><h1 class="text-h4">Drive Sync</h1><p class="text-medium-emphasis">Sincronización auditable de imágenes desde Google Drive</p></div><div class="d-flex ga-2"><v-btn variant="tonal" :loading="loading" @click="refresh">Actualizar</v-btn><v-btn v-if="active" color="error" variant="tonal" :loading="busy" @click="cancel">Cancelar</v-btn><v-btn color="primary" :disabled="!!active" :loading="busy" @click="start">Iniciar</v-btn></div></div><v-alert v-if="error" type="error" closable class="mb-4" @click:close="error=''">{{error}}</v-alert><v-row><v-col cols="12" lg="5"><v-card><v-card-title>Historial</v-card-title><v-data-table :items="runs" :loading="loading" :headers="[{title:'Inicio',key:'created_at'},{title:'Estado',key:'status'},{title:'Resultado',key:'success_count'},{title:'',key:'actions',sortable:false}]" density="compact"><template #item.created_at="{item}">{{item.created_at?new Date(item.created_at).toLocaleString():'-'}}</template><template #item.status="{item}"><v-chip size="small">{{item.status}}</v-chip></template><template #item.success_count="{item}">{{item.success_count}} / {{item.total_items}}</template><template #item.actions="{item}"><v-btn size="small" variant="text" @click="selectRun(item)">Ver</v-btn></template></v-data-table></v-card></v-col><v-col cols="12" lg="7"><v-card><v-card-title>Detalle {{selected?.id??''}}</v-card-title><v-card-text v-if="!selected" class="text-medium-emphasis">Seleccioná una ejecución.</v-card-text><template v-else><v-card-text><div class="d-flex ga-4 flex-wrap"><v-chip>{{selected.status}}</v-chip><span>Procesados: {{selected.success_count}}</span><span>Errores: {{selected.error_count}}</span><span>Omitidos: {{selected.skipped_count}}</span></div></v-card-text><v-data-table v-model="selectedItems" show-select item-value="id" :items="selected.items??[]" :headers="[{title:'Archivo',key:'filename'},{title:'SKU',key:'sku'},{title:'Estado',key:'status'},{title:'Error',key:'error_message'}]" density="compact"/><v-card-actions><v-spacer/><v-btn color="primary" :disabled="!selectedItems.length" :loading="busy" @click="retry">Reintentar seleccionados</v-btn></v-card-actions></template></v-card></v-col></v-row></v-container></template>
