<!-- NG-HEADER: Nombre de archivo: KnowledgeView.vue -->
<!-- NG-HEADER: Ubicación: frontend-vue/src/modules/admin/views/KnowledgeView.vue -->
<!-- NG-HEADER: Descripción: Administración y prueba del conocimiento RAG del diagnóstico de plantas. -->
<!-- NG-HEADER: Lineamientos: Ver AGENTS.md -->
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { deleteKnowledgeFile, deleteKnowledgeSource, getKnowledgeFiles, getKnowledgeStatus, indexKnowledge, listKnowledgeTasks, testRag, uploadKnowledge, type KnowledgeFile, type KnowledgeStatus, type KnowledgeTask, type RagResult } from '../../../services/adminOperations'
import { getHttpErrorMessage } from '../../../services/http'
const files=ref<KnowledgeFile[]>([]);const tasks=ref<KnowledgeTask[]>([]);const status=ref<KnowledgeStatus|null>(null);const results=ref<RagResult[]>([]);const query=ref('');const loading=ref(false);const error=ref('')
async function refresh(){loading.value=true;try{[files.value,status.value,tasks.value]=await Promise.all([getKnowledgeFiles(),getKnowledgeStatus(),listKnowledgeTasks()])}catch(e){error.value=getHttpErrorMessage(e)}finally{loading.value=false}}
async function upload(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];if(!file)return;loading.value=true;try{await uploadKnowledge(file);await refresh()}catch(e){error.value=getHttpErrorMessage(e)}finally{input.value='';loading.value=false}}
async function index(target:string,force=false){loading.value=true;try{await indexKnowledge(target,force);await refresh()}catch(e){error.value=getHttpErrorMessage(e)}finally{loading.value=false}}
async function remove(file:KnowledgeFile,removeFile=false){loading.value=true;try{if(removeFile)await deleteKnowledgeFile(file.path);else if(file.source_id)await deleteKnowledgeSource(file.source_id);await refresh()}catch(e){error.value=getHttpErrorMessage(e)}finally{loading.value=false}}
async function search(){if(!query.value.trim())return;loading.value=true;try{results.value=await testRag(query.value)}catch(e){error.value=getHttpErrorMessage(e)}finally{loading.value=false}}
onMounted(refresh)
</script>
<template><v-container fluid class="py-8"><div class="d-flex flex-wrap justify-space-between align-center ga-3 mb-6"><div><h1 class="text-h4">Conocimiento</h1><p class="text-medium-emphasis">Base vectorial RAG para diagnóstico de plantas</p></div><div class="d-flex ga-2"><v-btn variant="tonal" :loading="loading" @click="refresh">Actualizar</v-btn><v-btn color="primary" @click="index('folder')">Indexar pendientes</v-btn><v-btn variant="tonal" @click="index('folder',true)">Reindexar todo</v-btn><v-btn tag="label" prepend-icon="mdi-upload"><input type="file" accept=".md,.txt,.pdf" hidden @change="upload">Subir archivo</v-btn></div></div><v-alert v-if="error" type="error" closable class="mb-4" @click:close="error=''">{{error}}</v-alert><v-row class="mb-4"><v-col v-for="item in [{l:'Fuentes',v:status?.total_sources},{l:'Chunks',v:status?.total_chunks},{l:'Pendientes',v:status?.files_pending},{l:'Tareas activas',v:status?.tasks_running}]" :key="item.l" cols="6" md="3"><v-card><v-card-text><div class="text-caption">{{item.l}}</div><div class="text-h5">{{item.v??0}}</div></v-card-text></v-card></v-col></v-row><v-card><v-card-title>Archivos</v-card-title><v-data-table :items="files" :loading="loading" :headers="[{title:'Archivo',key:'filename'},{title:'Estado',key:'indexed'},{title:'Chunks',key:'chunks_count'},{title:'',key:'actions',sortable:false}]"><template #item.indexed="{item}"><v-chip size="small" :color="item.needs_reindex?'warning':item.indexed?'success':'default'">{{item.needs_reindex?'Desactualizado':item.indexed?'Indexado':'Pendiente'}}</v-chip></template><template #item.actions="{item}"><div class="d-flex ga-1 justify-end"><v-btn size="small" variant="text" @click="index(item.path,item.indexed)">Indexar</v-btn><v-btn v-if="item.source_id" size="small" variant="text" @click="remove(item)">Quitar índice</v-btn><v-btn size="small" color="error" variant="text" @click="remove(item,true)">Eliminar</v-btn></div></template></v-data-table></v-card><v-row class="mt-4"><v-col cols="12" lg="6"><v-card><v-card-title>Probar recuperación</v-card-title><v-card-text><v-textarea v-model="query" label="Síntomas o consulta" rows="3"/><v-btn color="primary" @click="search">Buscar contexto</v-btn><v-list><v-list-item v-for="result in results" :key="`${result.source}-${result.chunk_index}`" :title="`${result.source} · ${(result.similarity*100).toFixed(1)}%`" :subtitle="result.content"/></v-list></v-card-text></v-card></v-col><v-col cols="12" lg="6"><v-card><v-card-title>Tareas recientes</v-card-title><v-list><v-list-item v-for="task in tasks" :key="task.id" :title="`${task.type}: ${task.target}`" :subtitle="`${task.status} · ${task.progress}%${task.error?` · ${task.error}`:''}`"/></v-list></v-card></v-col></v-row></v-container></template>
