<!-- NG-HEADER: Nombre de archivo: SchedulerView.vue -->
<!-- NG-HEADER: Ubicación: frontend-vue/src/modules/admin/views/SchedulerView.vue -->
<!-- NG-HEADER: Descripción: Configuración persistente e historial del scheduler de mercado. -->
<!-- NG-HEADER: Lineamientos: Ver AGENTS.md -->
<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { getSchedulerStatus, listSchedulerRuns, runScheduler, saveScheduler, startScheduler, stopScheduler, type SchedulerRun, type SchedulerStatus } from '../../../services/adminOperations'
import { getHttpErrorMessage } from '../../../services/http'
const status=ref<SchedulerStatus|null>(null);const runs=ref<SchedulerRun[]>([]);const loading=ref(false);const error=ref('');const startHour=ref('02:00');const intervalHours=ref(24);const maxProducts=ref(50);const days=ref(2);const timezone=ref('America/Argentina/Buenos_Aires');const prioritize=ref(true)
async function refresh(){loading.value=true;try{status.value=await getSchedulerStatus();runs.value=(await listSchedulerRuns()).items;startHour.value=status.value.start_hour;intervalHours.value=status.value.interval_hours;maxProducts.value=status.value.max_products_per_run;days.value=status.value.update_frequency_days;timezone.value=status.value.timezone??timezone.value;prioritize.value=status.value.prioritize_mandatory}catch(e){error.value=getHttpErrorMessage(e)}finally{loading.value=false}}
async function action(kind:'start'|'stop'|'run'|'save'){loading.value=true;try{if(kind==='start')await startScheduler();if(kind==='stop')await stopScheduler();if(kind==='run')await runScheduler(maxProducts.value,days.value);if(kind==='save')await saveScheduler({start_hour:startHour.value,interval_hours:intervalHours.value,timezone:timezone.value,update_frequency_days:days.value,max_products_per_run:maxProducts.value,prioritize_mandatory:prioritize.value});await refresh()}catch(e){error.value=getHttpErrorMessage(e)}finally{loading.value=false}}
onMounted(refresh)
</script>
<template><v-container fluid class="py-8"><div class="d-flex justify-space-between align-center mb-6"><div><h1 class="text-h4">Scheduler de mercado</h1><p class="text-medium-emphasis">Configuración persistente y ejecuciones</p></div><v-btn variant="tonal" :loading="loading" @click="refresh">Actualizar</v-btn></div><v-alert v-if="error" type="error" closable class="mb-4" @click:close="error=''">{{error}}</v-alert><v-row><v-col cols="12" md="4"><v-card><v-card-title>Estado</v-card-title><v-card-text><v-chip :color="status?.running?'success':'default'">{{status?.running?'Activo':'Detenido'}}</v-chip><div class="mt-4">Próxima ejecución: {{status?.next_run_time?new Date(status.next_run_time).toLocaleString():'-'}}</div></v-card-text><v-card-actions><v-btn v-if="!status?.running" color="primary" @click="action('start')">Iniciar</v-btn><v-btn v-else color="error" variant="tonal" @click="action('stop')">Detener</v-btn></v-card-actions></v-card></v-col><v-col cols="12" md="4"><v-card><v-card-title>Configuración</v-card-title><v-card-text><v-text-field v-model="startHour" label="Hora de inicio"/><v-number-input v-model="intervalHours" label="Intervalo (horas)" :min="1" :max="24"/><v-text-field v-model="timezone" label="Zona horaria"/><v-switch v-model="prioritize" label="Priorizar fuentes obligatorias"/></v-card-text><v-card-actions><v-spacer/><v-btn color="primary" @click="action('save')">Guardar</v-btn></v-card-actions></v-card></v-col><v-col cols="12" md="4"><v-card><v-card-title>Ejecución manual</v-card-title><v-card-text><v-number-input v-model="maxProducts" label="Máximo de productos" :min="1" :max="500"/><v-number-input v-model="days" label="Antigüedad en días" :min="0" :max="365"/></v-card-text><v-card-actions><v-spacer/><v-btn color="primary" @click="action('run')">Ejecutar ahora</v-btn></v-card-actions></v-card></v-col></v-row><v-card class="mt-6"><v-card-title>Historial</v-card-title><v-data-table :items="runs" :headers="[{title:'Fecha',key:'created_at'},{title:'Tipo',key:'trigger'},{title:'Estado',key:'status'},{title:'Productos',key:'products_enqueued'},{title:'Duración',key:'duration_seconds'}]" density="compact"><template #item.created_at="{item}">{{item.created_at?new Date(item.created_at).toLocaleString():'-'}}</template><template #item.duration_seconds="{item}">{{item.duration_seconds??0}} s</template></v-data-table></v-card></v-container></template>
