<!-- NG-HEADER: Nombre de archivo: MarketDetailDrawer.vue -->
<!-- NG-HEADER: Ubicación: frontend-vue/src/modules/market/components/MarketDetailDrawer.vue -->
<!-- NG-HEADER: Descripción: Detalle, fuentes, validación, carga manual e histórico de Mercado. -->
<!-- NG-HEADER: Lineamientos: Ver AGENTS.md -->
<script setup lang="ts">
import { ref, watch } from 'vue'
import { getHttpErrorMessage } from '../../../services/http'
import { addMarketSource, createManualObservation, deleteMarketSource, discoverMarketSources, getMarketHistory, getProductSources, revalidateMarketSource } from '../api/market'
import type { HistoryPoint, MarketProduct, MarketSource, ProductSources } from '../types'
import MarketHistoryChart from './MarketHistoryChart.vue'
const props = defineProps<{ modelValue: boolean; product: MarketProduct | null }>()
const emit = defineEmits<{ 'update:modelValue': [value: boolean]; changed: [] }>()
const detail = ref<ProductSources | null>(null); const history = ref<HistoryPoint[]>([]); const loading = ref(false); const error = ref(''); const addOpen = ref(false); const manualOpen = ref(false); const manualSource = ref<MarketSource | null>(null); const manualPrice = ref<number | null>(null); const manualNote = ref(''); const suggestions = ref<Array<{ url: string; title: string; snippet: string }>>([])
const form = ref({ source_name: '', url: '', source_type: 'static' as 'static' | 'dynamic' | 'manual', is_mandatory: false, attested_argentina_delivery: false })
async function load() { if (!props.product) return; loading.value = true; error.value = ''; try { const [sources, points] = await Promise.all([getProductSources(props.product.product_id), getMarketHistory(props.product.product_id)]); detail.value = sources; history.value = points } catch (cause) { error.value = getHttpErrorMessage(cause) } finally { loading.value = false } }
watch(() => [props.modelValue, props.product?.product_id], ([open]) => { if (open) void load() })
async function add() { if (!props.product) return; try { await addMarketSource(props.product.product_id, { ...form.value, url: form.value.url.trim() || null }); addOpen.value = false; form.value = { source_name: '', url: '', source_type: 'static', is_mandatory: false, attested_argentina_delivery: false }; await load(); emit('changed') } catch (cause) { error.value = getHttpErrorMessage(cause) } }
async function remove(source: MarketSource) { if (!confirm(`¿Eliminar ${source.source_name}?`)) return; try { await deleteMarketSource(source.id); await load(); emit('changed') } catch (cause) { error.value = getHttpErrorMessage(cause) } }
function observe(source: MarketSource) { manualSource.value = source; manualPrice.value = source.last_price; manualNote.value = ''; manualOpen.value = true }
async function saveObservation() { if (!manualSource.value || !manualPrice.value) return; try { await createManualObservation(manualSource.value.id, manualPrice.value, manualNote.value || undefined); manualOpen.value = false; await load(); emit('changed') } catch (cause) { error.value = getHttpErrorMessage(cause) } }
async function revalidate(source: MarketSource) { try { await revalidateMarketSource(source.id); await load() } catch (cause) { error.value = getHttpErrorMessage(cause) } }
async function discover() { if (!props.product) return; try { suggestions.value = await discoverMarketSources(props.product.product_id) } catch (cause) { error.value = getHttpErrorMessage(cause) } }
function useSuggestion(item: { url: string; title: string }) { form.value = { ...form.value, source_name: item.title.slice(0, 200), url: item.url, source_type: 'static' }; addOpen.value = true }
const allSources = () => [...(detail.value?.mandatory ?? []), ...(detail.value?.additional ?? [])]
const money = (value: number | null | undefined) => value == null ? '—' : `$ ${value.toLocaleString('es-AR', { minimumFractionDigits: 2 })}`
</script>
<template><v-navigation-drawer :model-value="modelValue" location="right" temporary width="720" @update:model-value="emit('update:modelValue',$event)"><v-toolbar><v-toolbar-title>{{ product?.preferred_name || 'Mercado' }}</v-toolbar-title><v-btn icon="mdi-close" @click="emit('update:modelValue',false)" /></v-toolbar><div class="pa-5"><v-alert v-if="error" type="error" closable class="mb-4" @click:close="error=''">{{ error }}</v-alert><v-progress-linear v-if="loading" indeterminate class="mb-4" /><v-row v-if="detail"><v-col cols="4"><v-card variant="tonal"><v-card-text><div class="text-caption">Venta</div><strong>{{ money(detail.sale_price) }}</strong></v-card-text></v-card></v-col><v-col cols="4"><v-card variant="tonal"><v-card-text><div class="text-caption">Promedio</div><strong>{{ money(detail.market_price_reference) }}</strong></v-card-text></v-card></v-col><v-col cols="4"><v-card variant="tonal"><v-card-text><div class="text-caption">Rango</div><strong>{{ money(detail.market_price_min) }} – {{ money(detail.market_price_max) }}</strong></v-card-text></v-card></v-col></v-row><div class="d-flex ga-2 my-4"><v-btn color="primary" prepend-icon="mdi-plus" @click="addOpen=true">Agregar fuente</v-btn><v-btn variant="tonal" prepend-icon="mdi-web-search" @click="discover">Descubrir</v-btn></div><v-list lines="three"><v-list-item v-for="source in allSources()" :key="source.id"><template #prepend><v-icon :color="source.validation_status==='rejected'?'error':source.validation_status==='warning'?'warning':'success'" icon="mdi-web" /></template><v-list-item-title>{{ source.source_name }} <v-chip size="x-small">{{ source.source_type }}</v-chip></v-list-item-title><v-list-item-subtitle>{{ money(source.last_price) }} · {{ source.validation_status }} · {{ source.last_checked_at ? new Date(source.last_checked_at).toLocaleString('es-AR') : 'sin captura' }}<br>{{ source.url || 'Fuente manual sin URL' }}<span v-if="source.last_error_message" class="text-error"> · {{ source.last_error_message }}</span></v-list-item-subtitle><template #append><div class="d-flex"><v-btn icon="mdi-currency-usd" title="Cargar precio manual" variant="text" @click="observe(source)" /><v-btn icon="mdi-shield-refresh" title="Revalidar" variant="text" @click="revalidate(source)" /><v-btn icon="mdi-delete" title="Eliminar" color="error" variant="text" @click="remove(source)" /></div></template></v-list-item></v-list><v-card v-if="suggestions.length" class="my-4"><v-card-title>Sugerencias</v-card-title><v-list><v-list-item v-for="item in suggestions" :key="item.url" :title="item.title" :subtitle="item.url" @click="useSuggestion(item)" /></v-list></v-card><v-card class="mt-4"><v-card-title>Histórico del promedio</v-card-title><v-card-text><MarketHistoryChart :items="history" /></v-card-text></v-card></div></v-navigation-drawer>
<v-dialog v-model="addOpen" max-width="600"><v-card><v-card-title>Nueva fuente</v-card-title><v-card-text><v-text-field v-model="form.source_name" label="Competidor" /><v-select v-model="form.source_type" :items="[{title:'Estática',value:'static'},{title:'Dinámica / Chromium',value:'dynamic'},{title:'Manual libre',value:'manual'}]" label="Tipo" /><v-text-field v-if="form.source_type!=='manual'" v-model="form.url" label="URL" /><v-switch v-model="form.is_mandatory" label="Fuente obligatoria" /><v-checkbox v-if="form.source_type==='manual'" v-model="form.attested_argentina_delivery" label="Declaro que vende en ARS y entrega en Argentina" /></v-card-text><v-card-actions><v-spacer/><v-btn @click="addOpen=false">Cancelar</v-btn><v-btn color="primary" :disabled="!form.source_name.trim() || (form.source_type!=='manual'&&!form.url.trim())" @click="add">Crear</v-btn></v-card-actions></v-card></v-dialog>
<v-dialog v-model="manualOpen" max-width="520"><v-card><v-card-title>Precio manual · {{ manualSource?.source_name }}</v-card-title><v-card-text><v-text-field v-model.number="manualPrice" type="number" min="0.01" step="0.01" prefix="$" suffix="ARS" label="Precio" /><v-textarea v-model="manualNote" label="Nota de auditoría" rows="2" /></v-card-text><v-card-actions><v-spacer/><v-btn @click="manualOpen=false">Cancelar</v-btn><v-btn color="primary" :disabled="!manualPrice || manualPrice<=0" @click="saveObservation">Guardar observación</v-btn></v-card-actions></v-card></v-dialog></template>
