<!-- NG-HEADER: Nombre de archivo: MarketTable.vue -->
<!-- NG-HEADER: Ubicación: frontend-vue/src/modules/market/components/MarketTable.vue -->
<!-- NG-HEADER: Descripción: Tabla de Mercado con selección, cobertura y badge accesible. -->
<!-- NG-HEADER: Lineamientos: Ver AGENTS.md -->
<script setup lang="ts">
import MarketPriceBadge from './MarketPriceBadge.vue'
import type { MarketProduct } from '../types'
defineProps<{ items: MarketProduct[]; loading: boolean; selected: number[] }>()
const emit = defineEmits<{ 'update:selected': [ids: number[]]; detail: [item: MarketProduct]; editSale: [item: MarketProduct] }>()
const headers = [{ title: 'Producto', key: 'preferred_name' }, { title: 'Venta', key: 'sale_price', align: 'end' as const }, { title: 'Promedio mercado', key: 'market_price_reference', align: 'end' as const }, { title: 'Posición', key: 'position' }, { title: 'Cobertura', key: 'coverage' }, { title: 'Actualizado', key: 'last_market_update' }, { title: '', key: 'actions', sortable: false }]
const money = (value: number | null) => value === null ? '—' : `$ ${value.toLocaleString('es-AR', { minimumFractionDigits: 2 })}`
</script>
<template><v-data-table :headers="headers" :items="items" :loading="loading" :items-per-page="-1" show-select item-value="product_id" :model-value="selected" @update:model-value="emit('update:selected', $event as number[])"><template #item.preferred_name="{ item }"><div><strong>{{ item.preferred_name }}</strong><div class="text-caption text-medium-emphasis">{{ item.product_sku }}</div></div></template><template #item.sale_price="{ item }"><div class="d-flex justify-end align-center ga-1"><span>{{ money(item.sale_price) }}</span><v-btn icon="mdi-pencil" size="x-small" variant="text" title="Editar precio de venta" @click="emit('editSale', item)" /></div></template><template #item.market_price_reference="{ item }">{{ money(item.market_price_reference) }}</template><template #item.position="{ item }"><MarketPriceBadge :position="item.price_position" :delta="item.price_delta_pct" :label="item.comparison_label" /></template><template #item.coverage="{ item }"><div class="d-flex ga-1"><v-chip size="x-small" color="success">{{ item.effective_sources_count }} vigentes</v-chip><v-chip v-if="item.stale_sources_count" size="x-small" color="warning">{{ item.stale_sources_count }} vencidas</v-chip><v-chip v-if="item.warning_sources_count" size="x-small" color="warning" variant="outlined">{{ item.warning_sources_count }} advert.</v-chip></div></template><template #item.last_market_update="{ value }">{{ value ? new Date(value).toLocaleString('es-AR') : 'Nunca' }}</template><template #item.actions="{ item }"><v-btn variant="text" prepend-icon="mdi-open-in-new" @click="emit('detail', item)">Detalle</v-btn></template></v-data-table></template>
