"""add_rag_knowledge_tables

Revision ID: cf0f6e70fe89
Revises: c0467ef5320e
Create Date: 2025-11-25 18:58:01.516760
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy.vector

# revision identifiers, used by Alembic.
revision = 'cf0f6e70fe89'
down_revision = 'c0467ef5320e'
branch_labels = None
depends_on = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('meta_json', sa.JSON(), server_default='{}', nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_sources_created', 'knowledge_sources', ['created_at'], unique=False)
    op.create_index('ix_knowledge_sources_hash', 'knowledge_sources', ['hash'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_knowledge_chunks_embedding', 'knowledge_chunks', ['embedding'], unique=False, postgresql_using='ivfflat')
    op.create_index('ix_knowledge_chunks_source', 'knowledge_chunks', ['source_id'], unique=False)
    op.drop_table('sku_sequences')
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('canonical_products', 'specs_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('canonical_products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('canonical_products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('ux_customers_document_number'), table_name='customers', postgresql_where='(document_number IS NOT NULL)')
    op.alter_column('external_media_map', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_external_media_map_provider_product'), table_name='external_media_map')
    op.alter_column('image_job_logs', 'level',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('image_job_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_image_job_logs_job_created'), table_name='image_job_logs')
    op.alter_column('image_jobs', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('image_jobs', 'mode',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('image_jobs', 'retries',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('image_jobs', 'rate_rps',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('image_jobs', 'burst',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('image_jobs', 'log_retention_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('image_jobs', 'purge_ttl_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('image_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ux_image_jobs_name'), table_name='image_jobs')
    op.alter_column('image_reviews', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('image_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('image_reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_image_reviews_status'), table_name='image_reviews')
    op.alter_column('image_versions', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('image_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_image_versions_image_kind'), table_name='image_versions')
    op.alter_column('images', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('images', 'locked',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('images', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('images', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('images', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('import_job_rows', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('import_job_rows', 'row_json_normalized',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.drop_index(op.f('ix_import_job_rows_job_idx'), table_name='import_job_rows')
    op.drop_index(op.f('ix_import_job_rows_job_status'), table_name='import_job_rows')
    op.drop_column('import_job_rows', 'delta_compra')
    op.drop_column('import_job_rows', 'precio_venta')
    op.drop_column('import_job_rows', 'nombre')
    op.drop_column('import_job_rows', 'meta')
    op.drop_column('import_job_rows', 'delta_venta')
    op.drop_column('import_job_rows', 'precio_compra')
    op.drop_column('import_job_rows', 'error_msg')
    op.drop_column('import_job_rows', 'compra_minima')
    op.drop_column('import_job_rows', 'codigo')
    op.drop_column('import_job_rows', 'categoria_path')
    op.drop_column('import_job_rows', 'delta_pct')
    op.alter_column('import_jobs', 'filename',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
    op.alter_column('import_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('import_jobs', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_import_jobs_supplier'), table_name='import_jobs')
    op.drop_constraint(op.f('import_jobs_supplier_id_fkey'), 'import_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'import_jobs', 'suppliers', ['supplier_id'], ['id'])
    op.alter_column('import_logs', 'level',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('import_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('market_alerts', 'alert_type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('sale_vs_market', 'market_vs_previous', 'market_spike', 'market_drop', name='market_alert_type_enum'),
               existing_nullable=False)
    op.alter_column('market_alerts', 'severity',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('low', 'medium', 'high', 'critical', name='alert_severity_enum'),
               existing_nullable=False)
    op.alter_column('market_alerts', 'delta_percentage',
               existing_type=sa.NUMERIC(precision=8, scale=4),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    op.alter_column('market_alerts', 'resolved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('market_alerts', 'email_sent',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('market_alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('market_alerts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('market_price_history', 'currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
    op.alter_column('market_price_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('market_sources', 'is_mandatory',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('market_sources', 'currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=True)
    op.alter_column('market_sources', 'source_type',
               existing_type=postgresql.ENUM('static', 'dynamic', name='source_type_enum'),
               server_default=None,
               existing_nullable=True)
    op.alter_column('market_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('market_sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('price_history', 'price_old',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('price_history', 'price_new',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('price_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('product_equivalences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_equiv_canonical_product_id'), table_name='product_equivalences')
    op.drop_constraint(op.f('product_equivalences_supplier_product_id_fkey'), 'product_equivalences', type_='foreignkey')
    op.create_foreign_key(None, 'product_equivalences', 'supplier_products', ['supplier_product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'is_enriching',
               existing_type=sa.BOOLEAN(),
               server_default='false',
               existing_nullable=False)
    op.alter_column('purchase_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('purchase_lines', 'qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('purchase_lines', 'unit_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('purchase_lines', 'line_discount',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('purchase_lines', 'state',
               existing_type=sa.VARCHAR(length=24),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('purchase_lines_product_id_fkey'), 'purchase_lines', type_='foreignkey')
    op.drop_constraint(op.f('purchase_lines_supplier_item_id_fkey'), 'purchase_lines', type_='foreignkey')
    op.create_foreign_key(None, 'purchase_lines', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'purchase_lines', 'supplier_products', ['supplier_item_id'], ['id'], ondelete='CASCADE')
    op.drop_column('purchase_lines', 'meta')
    op.alter_column('purchases', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('purchases', 'global_discount',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('purchases', 'vat_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('purchases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('purchases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('return_lines', 'qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('return_lines', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('return_lines', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_return_lines_product_id'), table_name='return_lines')
    op.drop_index(op.f('ix_return_lines_return_id'), table_name='return_lines')
    op.alter_column('returns', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('returns', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('returns', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('ix_returns_sale_id'), table_name='returns')
    op.alter_column('sale_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('sale_lines', 'qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sale_lines', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sale_lines', 'line_discount',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('sale_lines', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('sale_lines', 'tax',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('sale_lines', 'total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=True)
    op.alter_column('sale_lines', 'state',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_sale_lines_product_id'), table_name='sale_lines')
    op.drop_index(op.f('ix_sale_lines_product_sale'), table_name='sale_lines')
    op.drop_column('sale_lines', 'line_discount_percent')
    op.alter_column('sale_payments', 'method',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sale_payments', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sale_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.add_column('sales', sa.Column('meta', sa.JSON(), nullable=True))
    op.alter_column('sales', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sales', 'sale_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('sales', 'sale_kind',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sales', 'discount_percent',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=None,
               nullable=True)
    op.alter_column('sales', 'discount_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               nullable=True)
    op.alter_column('sales', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sales', 'tax',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sales', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sales', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('sales', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.drop_index(op.f('ix_sales_customer_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_customer_id'), table_name='sales')
    op.drop_index(op.f('ix_sales_sale_date'), table_name='sales')
    op.drop_index(op.f('ix_sales_status'), table_name='sales')
    op.drop_index(op.f('ix_sales_status_date'), table_name='sales')
    op.drop_column('sales', 'metadata')
    op.alter_column('service_logs', 'ok',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('service_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('services', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('services', 'auto_start',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('services', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('sessions', 'id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('sessions', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('sessions', 'csrf_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('sessions', 'ip',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('sessions', 'user_agent',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.alter_column('startup_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.alter_column('stock_ledger', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('supplier_files_supplier_id_fkey'), 'supplier_files', type_='foreignkey')
    op.create_foreign_key(None, 'supplier_files', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.alter_column('supplier_price_history', 'file_fk',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_price_hist_supplier_product'), table_name='supplier_price_history')
    op.drop_index(op.f('ix_sph_product_date'), table_name='supplier_price_history')
    op.drop_constraint(op.f('fk_sph_product'), 'supplier_price_history', type_='foreignkey')
    op.drop_constraint(op.f('supplier_price_history_supplier_product_fk_fkey'), 'supplier_price_history', type_='foreignkey')
    op.drop_constraint(op.f('fk_sph_supplier'), 'supplier_price_history', type_='foreignkey')
    op.drop_constraint(op.f('fk_sph_job'), 'supplier_price_history', type_='foreignkey')
    op.create_foreign_key(None, 'supplier_price_history', 'supplier_products', ['supplier_product_fk'], ['id'], ondelete='CASCADE')
    op.drop_column('supplier_price_history', 'precio_venta')
    op.drop_column('supplier_price_history', 'job_id')
    op.drop_column('supplier_price_history', 'product_id')
    op.drop_column('supplier_price_history', 'precio_compra')
    op.drop_column('supplier_price_history', 'supplier_id')
    op.drop_index(op.f('ix_supplier_products_internal_variant_id'), table_name='supplier_products')
    op.drop_constraint(op.f('supplier_products_internal_variant_id_fkey'), 'supplier_products', type_='foreignkey')
    op.drop_constraint(op.f('supplier_products_internal_product_id_fkey'), 'supplier_products', type_='foreignkey')
    op.create_foreign_key(None, 'supplier_products', 'variants', ['internal_variant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'supplier_products', 'products', ['internal_product_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_preferences', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ux_user_preferences_user_scope'), table_name='user_preferences')
    op.create_unique_constraint('ux_user_preferences_user_scope', 'user_preferences', ['user_id', 'scope'])
    op.alter_column('users', 'identifier',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_users_identifier'), 'users', type_='unique')
    op.drop_constraint(op.f('users_identifier_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_identifier'), 'users', ['identifier'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_identifier'), table_name='users')
    op.create_unique_constraint(op.f('users_identifier_key'), 'users', ['identifier'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_users_identifier'), 'users', ['identifier'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'identifier',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               nullable=False)
    op.drop_constraint('ux_user_preferences_user_scope', 'user_preferences', type_='unique')
    op.create_index(op.f('ux_user_preferences_user_scope'), 'user_preferences', ['user_id', 'scope'], unique=True)
    op.alter_column('user_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('user_preferences', 'data',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               server_default=sa.text("'{}'::json"),
               existing_nullable=False)
    op.drop_constraint(None, 'supplier_products', type_='foreignkey')
    op.drop_constraint(None, 'supplier_products', type_='foreignkey')
    op.create_foreign_key(op.f('supplier_products_internal_product_id_fkey'), 'supplier_products', 'products', ['internal_product_id'], ['id'])
    op.create_foreign_key(op.f('supplier_products_internal_variant_id_fkey'), 'supplier_products', 'variants', ['internal_variant_id'], ['id'])
    op.create_index(op.f('ix_supplier_products_internal_variant_id'), 'supplier_products', ['internal_variant_id'], unique=False)
    op.add_column('supplier_price_history', sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('supplier_price_history', sa.Column('precio_compra', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('supplier_price_history', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('supplier_price_history', sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('supplier_price_history', sa.Column('precio_venta', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'supplier_price_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_sph_job'), 'supplier_price_history', 'import_jobs', ['job_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_sph_supplier'), 'supplier_price_history', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('supplier_price_history_supplier_product_fk_fkey'), 'supplier_price_history', 'supplier_products', ['supplier_product_fk'], ['id'])
    op.create_foreign_key(op.f('fk_sph_product'), 'supplier_price_history', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_sph_product_date'), 'supplier_price_history', ['supplier_product_fk', 'as_of_date'], unique=False)
    op.create_index(op.f('ix_price_hist_supplier_product'), 'supplier_price_history', ['supplier_id', 'product_id'], unique=False)
    op.alter_column('supplier_price_history', 'file_fk',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'supplier_files', type_='foreignkey')
    op.create_foreign_key(op.f('supplier_files_supplier_id_fkey'), 'supplier_files', 'suppliers', ['supplier_id'], ['id'])
    op.alter_column('stock_ledger', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('startup_metrics', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.alter_column('sessions', 'user_agent',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sessions', 'ip',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('sessions', 'csrf_token',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('sessions', 'role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('sessions', 'id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('services', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('services', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('services', 'auto_start',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('services', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'stopped'::character varying"),
               existing_nullable=False)
    op.alter_column('service_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('service_logs', 'ok',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.add_column('sales', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_sales_status_date'), 'sales', ['status', 'sale_date'], unique=False)
    op.create_index(op.f('ix_sales_status'), 'sales', ['status'], unique=False)
    op.create_index(op.f('ix_sales_sale_date'), 'sales', ['sale_date'], unique=False)
    op.create_index(op.f('ix_sales_customer_id'), 'sales', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_customer_date'), 'sales', ['customer_id', 'sale_date'], unique=False)
    op.alter_column('sales', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('sales', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('sales', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('sales', 'tax',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('sales', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('sales', 'discount_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               nullable=False)
    op.alter_column('sales', 'discount_percent',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=sa.text("'0'::numeric"),
               nullable=False)
    op.alter_column('sales', 'sale_kind',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'MOSTRADOR'::character varying"),
               existing_nullable=False)
    op.alter_column('sales', 'sale_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('sales', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'CONFIRMADA'::character varying"),
               existing_nullable=False)
    op.drop_column('sales', 'meta')
    op.alter_column('sale_payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('sale_payments', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('sale_payments', 'method',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'efectivo'::character varying"),
               existing_nullable=False)
    op.add_column('sale_lines', sa.Column('line_discount_percent', sa.NUMERIC(precision=6, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_sale_lines_product_sale'), 'sale_lines', ['product_id', 'sale_id'], unique=False)
    op.create_index(op.f('ix_sale_lines_product_id'), 'sale_lines', ['product_id'], unique=False)
    op.alter_column('sale_lines', 'state',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'OK'::character varying"),
               existing_nullable=True)
    op.alter_column('sale_lines', 'total',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('sale_lines', 'tax',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('sale_lines', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('sale_lines', 'line_discount',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('sale_lines', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('sale_lines', 'qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('sale_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.create_index(op.f('ix_returns_sale_id'), 'returns', ['sale_id'], unique=False)
    op.alter_column('returns', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('returns', 'total_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('returns', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'REGISTRADA'::character varying"),
               existing_nullable=False)
    op.create_index(op.f('ix_return_lines_return_id'), 'return_lines', ['return_id'], unique=False)
    op.create_index(op.f('ix_return_lines_product_id'), 'return_lines', ['product_id'], unique=False)
    op.alter_column('return_lines', 'subtotal',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('return_lines', 'unit_price',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('return_lines', 'qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('purchases', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('purchases', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('purchases', 'vat_rate',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('purchases', 'global_discount',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('purchases', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'BORRADOR'::character varying"),
               existing_nullable=False)
    op.add_column('purchase_lines', sa.Column('meta', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'purchase_lines', type_='foreignkey')
    op.drop_constraint(None, 'purchase_lines', type_='foreignkey')
    op.create_foreign_key(op.f('purchase_lines_supplier_item_id_fkey'), 'purchase_lines', 'supplier_products', ['supplier_item_id'], ['id'])
    op.create_foreign_key(op.f('purchase_lines_product_id_fkey'), 'purchase_lines', 'products', ['product_id'], ['id'])
    op.alter_column('purchase_lines', 'state',
               existing_type=sa.VARCHAR(length=24),
               server_default=sa.text("'OK'::character varying"),
               existing_nullable=False)
    op.alter_column('purchase_lines', 'line_discount',
               existing_type=sa.NUMERIC(precision=6, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=True)
    op.alter_column('purchase_lines', 'unit_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('purchase_lines', 'qty',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               server_default=sa.text("'0'::numeric"),
               existing_nullable=False)
    op.alter_column('purchase_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('products', 'is_enriching',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(None, 'product_equivalences', type_='foreignkey')
    op.create_foreign_key(op.f('product_equivalences_supplier_product_id_fkey'), 'product_equivalences', 'supplier_products', ['supplier_product_id'], ['id'])
    op.create_index(op.f('ix_equiv_canonical_product_id'), 'product_equivalences', ['canonical_product_id'], unique=False)
    op.alter_column('product_equivalences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('price_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('price_history', 'price_new',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('price_history', 'price_old',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('market_sources', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('market_sources', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('market_sources', 'source_type',
               existing_type=postgresql.ENUM('static', 'dynamic', name='source_type_enum'),
               server_default=sa.text("'static'::source_type_enum"),
               existing_nullable=True)
    op.alter_column('market_sources', 'currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'ARS'::character varying"),
               existing_nullable=True)
    op.alter_column('market_sources', 'is_mandatory',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('market_price_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('market_price_history', 'currency',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'ARS'::character varying"),
               existing_nullable=False)
    op.alter_column('market_alerts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('market_alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('market_alerts', 'email_sent',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('market_alerts', 'resolved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('market_alerts', 'delta_percentage',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=8, scale=4),
               existing_nullable=False)
    op.alter_column('market_alerts', 'severity',
               existing_type=sa.Enum('low', 'medium', 'high', 'critical', name='alert_severity_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('market_alerts', 'alert_type',
               existing_type=sa.Enum('sale_vs_market', 'market_vs_previous', 'market_spike', 'market_drop', name='market_alert_type_enum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('import_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('import_logs', 'level',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'INFO'::character varying"),
               existing_nullable=False)
    op.drop_constraint(None, 'import_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('import_jobs_supplier_id_fkey'), 'import_jobs', 'suppliers', ['supplier_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_import_jobs_supplier'), 'import_jobs', ['supplier_id'], unique=False)
    op.alter_column('import_jobs', 'status',
               existing_type=sa.String(length=20),
               server_default=sa.text("'DRY_RUN'::character varying"),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('import_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('import_jobs', 'filename',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.add_column('import_job_rows', sa.Column('delta_pct', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True))
    op.add_column('import_job_rows', sa.Column('categoria_path', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('import_job_rows', sa.Column('codigo', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('import_job_rows', sa.Column('compra_minima', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('import_job_rows', sa.Column('error_msg', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('import_job_rows', sa.Column('precio_compra', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('import_job_rows', sa.Column('delta_venta', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('import_job_rows', sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('import_job_rows', sa.Column('nombre', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('import_job_rows', sa.Column('precio_venta', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('import_job_rows', sa.Column('delta_compra', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_import_job_rows_job_status'), 'import_job_rows', ['job_id', 'status'], unique=False)
    op.create_index(op.f('ix_import_job_rows_job_idx'), 'import_job_rows', ['job_id', 'row_index'], unique=False)
    op.alter_column('import_job_rows', 'row_json_normalized',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('import_job_rows', 'status',
               existing_type=sa.String(length=20),
               server_default=sa.text("'ok'::character varying"),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('images', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('images', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('images', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('images', 'locked',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('images', 'is_primary',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index(op.f('ix_image_versions_image_kind'), 'image_versions', ['image_id', 'kind'], unique=False)
    op.alter_column('image_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('image_versions', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.create_index(op.f('ix_image_reviews_status'), 'image_reviews', ['status'], unique=False)
    op.alter_column('image_reviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('image_reviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('image_reviews', 'status',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.create_index(op.f('ux_image_jobs_name'), 'image_jobs', ['name'], unique=True)
    op.alter_column('image_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('image_jobs', 'purge_ttl_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('30'),
               existing_nullable=False)
    op.alter_column('image_jobs', 'log_retention_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('90'),
               existing_nullable=False)
    op.alter_column('image_jobs', 'burst',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('image_jobs', 'rate_rps',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'1'::double precision"),
               existing_nullable=True)
    op.alter_column('image_jobs', 'retries',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('image_jobs', 'mode',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'off'::character varying"),
               existing_nullable=False)
    op.alter_column('image_jobs', 'active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index(op.f('ix_image_job_logs_job_created'), 'image_job_logs', ['job_name', 'created_at'], unique=False)
    op.alter_column('image_job_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('image_job_logs', 'level',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'INFO'::character varying"),
               existing_nullable=False)
    op.create_index(op.f('ix_external_media_map_provider_product'), 'external_media_map', ['provider', 'product_id'], unique=True)
    op.alter_column('external_media_map', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.create_index(op.f('ux_customers_document_number'), 'customers', ['document_number'], unique=True, postgresql_where='(document_number IS NOT NULL)')
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('customers', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('canonical_products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('canonical_products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('canonical_products', 'specs_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_table('sku_sequences',
    sa.Column('category_code', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('next_seq', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('category_code', name=op.f('sku_sequences_pkey'))
    )
    op.drop_index('ix_knowledge_chunks_source', table_name='knowledge_chunks')
    op.drop_index('ix_knowledge_chunks_embedding', table_name='knowledge_chunks', postgresql_using='ivfflat')
    op.drop_table('knowledge_chunks')
    op.drop_index('ix_knowledge_sources_hash', table_name='knowledge_sources')
    op.drop_index('ix_knowledge_sources_created', table_name='knowledge_sources')
    op.drop_table('knowledge_sources')
    # ### end Alembic commands ###
