supplier_name: "Santa Planta"
slug: "santa-planta"
# El archivo original es Excel (.xlsx)
file_type: "xlsx"
# Tomar la primera hoja del libro
sheet_name: 0
# Encabezados en la primera fila
header_row: 0
columns:
  supplier_product_id: ["ID"]
  title: ["Producto"]
  category_level_1: ["Agrupamiento"]
  category_level_2: ["Familia"]
  category_level_3: ["SubFamilia"]
  min_purchase_qty: ["Compra Minima"]
  supplier_stock: ["Stock"]
  purchase_price: ["PrecioDeCompra"]
  sale_price: ["PrecioDeVenta"]
transform:
  purchase_price:
    # Permite manejar planillas/csv con coma decimal
    replace_comma_decimal: true
  sale_price:
    replace_comma_decimal: true
encoding: "utf-8"
# Si el proveedor envía CSV como alternativa, usa ';' como separador
delimiter: ";"
defaults:
  status: "draft"
  stock_qty: 0
  min_qty: 0
category_map: {}
