<!-- NG-HEADER: Nombre de archivo: MarketView.vue -->
<!-- NG-HEADER: Ubicación: frontend-vue/src/modules/market/views/MarketView.vue -->
<!-- NG-HEADER: Descripción: Vista principal nativa Vue del módulo Mercado. -->
<!-- NG-HEADER: Lineamientos: Ver AGENTS.md -->
<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { listProductCategories, listProductSuppliers } from '../../products/api/products'
import type { ProductCategory, ProductSupplier } from '../../products/types'
import { useToastStore } from '../../../app/notifications/store'
import { getHttpErrorMessage } from '../../../services/http'
import { refreshProduct, refreshProducts, updateSalePrice } from '../api/market'
import { useMarketJob } from '../composables/useMarketJob'
import { useMarketProducts } from '../composables/useMarketProducts'
import type { MarketProduct } from '../types'
import MarketDetailDrawer from '../components/MarketDetailDrawer.vue'
import MarketTable from '../components/MarketTable.vue'
const { items, total, pages, loading, error, filters, setFilters, refresh } = useMarketProducts(); const { job, error: jobError, follow } = useMarketJob(); const toasts = useToastStore()
const selected = ref<number[]>([]); const detailProduct = ref<MarketProduct | null>(null); const detailOpen = ref(false); const saleOpen = ref(false); const saleProduct = ref<MarketProduct | null>(null); const salePrice = ref<number | null>(null); const busy = ref(false); const categories = ref<ProductCategory[]>([]); const suppliers = ref<ProductSupplier[]>([])
onMounted(async () => { try { [categories.value, suppliers.value] = await Promise.all([listProductCategories('category'), listProductSuppliers()]) } catch { /* filtros opcionales */ } })
watch(job, (value) => {
  if (value && ['partial', 'succeeded', 'failed', 'cancelled'].includes(value.status)) void refresh()
})
function detail(item: MarketProduct) { detailProduct.value = item; detailOpen.value = true }
function editSale(item: MarketProduct) { saleProduct.value = item; salePrice.value = item.sale_price; saleOpen.value = true }
async function saveSale() { if (!saleProduct.value || !salePrice.value) return; busy.value = true; try { await updateSalePrice(saleProduct.value.product_id, salePrice.value); saleOpen.value = false; await refresh() } catch (cause) { toasts.show(getHttpErrorMessage(cause), 'error') } finally { busy.value = false } }
async function runSelected() { if (!selected.value.length) return; busy.value = true; try { const response = await refreshProducts(selected.value); const first = response.results.find(item => item.job_id)?.job_id; if (first) void follow(first); toasts.show(`${selected.value.length} producto(s) enviados a Mercado`, 'success'); selected.value = [] } catch (cause) { toasts.show(getHttpErrorMessage(cause), 'error') } finally { busy.value = false } }
async function runOne() { if (!detailProduct.value) return; busy.value = true; try { const result = await refreshProduct(detailProduct.value.product_id); void follow(result.market_job_id); toasts.show(result.deduplicated ? 'Se reutilizó el trabajo activo' : 'Actualización encolada', 'info') } catch (cause) { toasts.show(getHttpErrorMessage(cause), 'error') } finally { busy.value = false } }
</script>
<template><v-container fluid class="py-8"><div class="d-flex justify-space-between align-center flex-wrap ga-3 mb-6"><div><h1 class="text-h4">Mercado</h1><p class="text-medium-emphasis">Precio promedio ARS, fuentes competidoras e histórico auditable</p></div><div class="d-flex ga-2"><v-btn :disabled="!selected.length" :loading="busy" color="primary" prepend-icon="mdi-refresh" @click="runSelected">Actualizar {{ selected.length || '' }}</v-btn><v-btn v-if="detailProduct" variant="tonal" :loading="busy" @click="runOne">Actualizar abierto</v-btn></div></div><v-alert v-if="error || jobError" type="error" closable class="mb-4">{{ error || jobError }}</v-alert><v-alert v-if="job" :type="job.status==='failed'?'error':job.status==='partial'?'warning':'info'" variant="tonal" class="mb-4">Job {{ job.id.slice(0,8) }} · {{ job.status }} · {{ job.processed_items }}/{{ job.total_items }}</v-alert><v-card class="mb-4"><v-card-text><v-row><v-col cols="12" md="5"><v-text-field :model-value="filters.q" label="Buscar producto o SKU" prepend-inner-icon="mdi-magnify" clearable hide-details @update:model-value="setFilters({q:$event || ''})" /></v-col><v-col cols="12" md="3"><v-select :model-value="filters.category_id" :items="categories" item-title="name" item-value="id" label="Categoría" clearable hide-details @update:model-value="setFilters({category_id:$event})" /></v-col><v-col cols="12" md="3"><v-select :model-value="filters.supplier_id" :items="suppliers" item-title="name" item-value="id" label="Proveedor" clearable hide-details @update:model-value="setFilters({supplier_id:$event})" /></v-col><v-col cols="12" md="1" class="d-flex align-center"><v-btn icon="mdi-refresh" variant="text" @click="refresh" /></v-col></v-row></v-card-text></v-card><v-card><MarketTable v-model:selected="selected" :items="items" :loading="loading" @detail="detail" @edit-sale="editSale" /><v-card-actions class="justify-space-between"><span class="text-caption">{{ total }} productos</span><v-pagination :model-value="filters.page" :length="Math.max(1,pages)" density="comfortable" @update:model-value="setFilters({page:$event},false)" /></v-card-actions></v-card><MarketDetailDrawer v-model="detailOpen" :product="detailProduct" @changed="refresh" /><v-dialog v-model="saleOpen" max-width="440"><v-card><v-card-title>Precio de venta</v-card-title><v-card-text><v-text-field v-model.number="salePrice" type="number" min="0.01" step="0.01" prefix="$" suffix="ARS" :label="saleProduct?.preferred_name" /></v-card-text><v-card-actions><v-spacer/><v-btn @click="saleOpen=false">Cancelar</v-btn><v-btn color="primary" :loading="busy" :disabled="!salePrice || salePrice<=0" @click="saveSale">Guardar</v-btn></v-card-actions></v-card></v-dialog></v-container></template>
